
#Husbandry Plus Settings
[common]
	#A list of biomes where maple trees can naturally generate. The list doesn't include maple forests.
	"Maple Tree Biomes" = ["minecraft:forest", "minecraft:wooded_hills", "minecraft:flower_forest"]
	#A list of biomes where snails can spawn. The list doesn't include maple forests.
	"Snail Spawn Biomes" = []
	#A list of items that can be used to breed snails.
	"Snail Breeding Items" = ["minecraft:mushroom_stew", "minecraft:suspicious_stew"]
	#A list of items that can be fed to snails to produce snail slime.
	"Snail Food" = ["minecraft:brown_mushroom", "minecraft:red_mushroom", "minecraft:mushroom_stem", "minecraft:brown_mushroom_block", "minecraft:red_mushroom_block", "quark:glowshroom", "quark:glowshroom_stem", "quark:glowshroom_block"]
	#A list of blocks snails can eat to produce snail slime.
	"Snail Block Food" = ["minecraft:brown_mushroom", "minecraft:red_mushroom", "quark:glowshroom"]

